### ISSUE TITLE
Some questions regarding the data

### ISSUE THREAD

**Issue by HilbertXu** [NUS-LinS-Lab/ManiFM#1]
Hi,

Thanks for your amazing work!
When I was going through your paper and code, I found that the wrench values are used for calculating the per-point motions for rigid objects and for the mpm&deformable objects, the difference between target pointcloud and the initial pointcloud is regarded as per-point motions. The related code snippets can be found:
[rigid objects](https://github.com/NUS-LinS-Lab/ManiFM/blob/6d11334acdbb2d792cfb09f235d2ca8638e2ebb6/dataset/dataset_rigidbody.py#L315)
[deformable objects](https://github.com/NUS-LinS-Lab/ManiFM/blob/6d11334acdbb2d792cfb09f235d2ca8638e2ebb6/dataset/dataset_deformable.py#L165)
[mpm objects](https://github.com/NUS-LinS-Lab/ManiFM/blob/6d11334acdbb2d792cfb09f235d2ca8638e2ebb6/dataset/dataset_mpm.py#L157)
I'm wondering whether this calculation process is the "flow model" illustrated in the Figure. 2 and Figure. 3. 

Moreover, I noticed that in the rigid object dataset script, there is a function for generating random wrench for an object, and this function is turned on in the training script. Why do you add such a random function given the wrench value in the training data. cause from my understanding, the wrench value should be related with the contact heatmap and the force heatmap. If my understanding is not correct, please feel free to point it out. I would sincerely appreciate your correction :p 
btw, I'm also wondering how you set the wrench values for rigid objects in real robot experiments. 

Thanks in avdance for your patient and kind help!

Cheers,
Yucheng

**Comment by ariszxxu** [comment]
Yucheng, thanks for your attention. Since we have discussed it, I'm closing the issue now. :)
